In [ ]:
from google.colab import files
uploaded = files.upload()

Saving df.csv to df.csv

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("df.csv")
df

     index     A      B     C     D       E     F      G     H     I  type
0        0  1.67  16.10  4.42  2.32  101.77  0.88  13.31  0.00  0.00     2
1        1  1.67  16.27  4.64  2.79  101.43  0.96  12.74  0.00  0.00     1
2        2  1.67  17.72  4.88  0.55  100.83  0.04  14.40  0.00  0.00     0
3        3  1.68  15.97  4.65  1.56  100.79  0.18  16.27  0.00  0.05     0
4        4  1.67  15.28  2.41  3.53  101.77  0.90  16.14  0.00  0.00     3
..     ...   ...    ...   ...   ...     ...   ...    ...   ...   ...   ...
209    209  1.67  17.83  2.86  3.91   98.36  1.14  15.62  0.00  0.00     5
210    210  1.68  13.22  0.00  1.42  102.31  0.00  23.94  0.00  0.00     1
211    211  1.67  16.64  0.00  4.83  102.52  0.21  15.06  1.38  0.02     5
212    212  1.67  16.06  0.00  2.66  101.15  0.50  20.00  0.00  0.00     3
213    213  1.67  16.67  4.59  2.51  100.53  0.76  14.05  0.19  0.00     0

[214 rows x 11 columns]

In [ ]:
n_rows = len(df)
n_rows

214

In [ ]:
column_names = df.columns
column_names

Index(['index', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'type'], dtype='object')

In [ ]:
dimensions = df.shape
dimensions

(214, 11)

In [ ]:
df.describe()

,index,A,B,C,D,E,F,G,H,I,type
count,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000
mean,106.500000,1.670467,16.089626,3.489813,2.745140,101.711215,0.745748,14.330888,0.297710,0.102757,1.542056
std,61.920648,0.003324,0.979979,1.875170,0.948929,1.084305,0.978743,2.276731,0.845669,0.175548,1.707648
min,0.000000,1.660000,12.880000,0.000000,0.550000,97.730000,0.000000,8.690000,0.000000,0.000000,0.000000
25%,53.250000,1.670000,15.490000,2.752500,2.260000,101.190000,0.185000,13.180000,0.000000,0.000000,0.000000
50%,106.500000,1.670000,15.960000,4.520000,2.580000,101.910000,0.830000,13.760000,0.000000,0.000000,1.000000
75%,159.750000,1.670000,16.592500,4.680000,3.100000,102.325000,0.920000,14.677500,0.000000,0.180000,2.000000
max,213.000000,1.690000,20.860000,5.840000,6.650000,105.570000,9.320000,25.900000,5.360000,0.920000,5.000000